# Generated by Django 6.0.2 on 2026-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeractivity_id_alter_customeractivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivity',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
