# Generated by Django 6.0.2 on 2026-04-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeruser_age_customeruser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='age',
        ),
    ]
