# Generated by Django 6.0.2 on 2026-04-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customeruser_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeractivity',
            options={'verbose_name_plural': 'All Users'},
        ),
    ]
