# Generated by Django 6.0.2 on 2026-04-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customeractivity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeractivity',
            options={'verbose_name_plural': 'Customer Activities'},
        ),
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'Customer User', 'verbose_name_plural': 'Customer Users'},
        ),
    ]
