# Generated by Django 6.0.2 on 2026-04-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customeractivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivity',
            name='product_ids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
