# Generated by Django 6.0.2 on 2026-04-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customeractivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name_plural': 'All Users'},
        ),
    ]
