# Generated by Django 6.0.2 on 2026-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customeruser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_home', 'View Home'), ('view_dashboard', 'View Dashboard'), ('view_product', 'View Product'), ('view_category', 'View Category'), ('view_orders', 'View Orders'), ('delete_order', 'Delete Order'), ('search', 'Search'), ('add_to_cart', 'Add To Cart'), ('remove_from_cart', 'Remove From Cart'), ('checkout', 'Checkout'), ('purchase_success', 'Purchase Success'), ('purchase_failed', 'Purchase Failed'), ('update_profile', 'Update Profile'), ('view_whistles', 'View Whistles'), ('add_whistle', 'Add Whistle'), ('remove_whistles', 'Remove Whistles')], max_length=50),
        ),
    ]
