# Generated by Django 6.0.2 on 2026-04-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customeractivity_product_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeractivity',
            name='product_ids',
        ),
    ]
