# Generated by Django 6.0.2 on 2026-04-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customeractivity_product_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivity',
            name='product_ids',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
