# Generated by Django 6.0.2 on 2026-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customeractivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivity',
            name='extra_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
