# Generated by Django 6.0.2 on 2026-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customeractivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
