# Generated by Django 6.0.2 on 2026-04-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customeruser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='has_set_interests',
            field=models.BooleanField(default=False),
        ),
    ]
