# Generated by Django 6.0.2 on 2026-05-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customeruser_has_set_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Seller'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
