# Generated by Django 6.0.2 on 2026-05-07 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churn_probability', models.FloatField()),
                ('will_churn', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Churn Records',
                'ordering': ['-scored_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('discount', 'Discount Offer'), ('recommendations', 'Product Recommendations'), ('winback', 'Win Back')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('was_sent', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Retention Emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
