# Generated by Django 6.0.2 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_whistle',
            field=models.BooleanField(default=False),
        ),
    ]
