# Generated by Django 6.0.2 on 2026-04-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discountPercentage', models.FloatField()),
                ('rating', models.FloatField()),
                ('stock', models.IntegerField()),
                ('tags', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('weight', models.FloatField()),
                ('dimensions', models.CharField(max_length=100)),
                ('warrantyInformation', models.CharField(max_length=200)),
                ('shippingInformation', models.CharField(max_length=200)),
                ('availabilityStatus', models.CharField(max_length=50)),
                ('reviews', models.TextField()),
                ('returnPolicy', models.CharField(max_length=200)),
                ('minimumOrderQuantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('thumbnail', models.ImageField(upload_to='products/thumbnails/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
