# Generated by Django 6.0.2 on 2026-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_brand_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageurl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
