# Generated by Django 6.0.2 on 2026-04-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageurl',
            new_name='image_url',
        ),
    ]
