# Generated by Django 6.0.2 on 2026-04-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_availability_status_product_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products Table'},
        ),
    ]
