# Generated by Django 6.0.2 on 2026-04-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maximum_order_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_order_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
