# Generated by Django 6.0.2 on 2026-04-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_availability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_whistle',
        ),
    ]
