# Generated by Django 6.0.2 on 2026-04-29 13:30

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_is_whistle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[products.models.validate_image_size]),
        ),
    ]
